In [216]:
import numpy as np

In [217]:
mat = np.zeros(81,np.float64)
mat = mat.reshape(9,9)

In [218]:
i = 0
# 쥐 한마리가 방 안을 배회한다.
# 방의 연결 구조를 담은 배열
arr1= [2,4,0,1,3,5,0,2,6,0,1,2,5,0,1,2,3,4,6,7,8,0,2,3,5,8,9,0,4,8,0,5,6,7,9,0,6,8,0]

#방의 연결, 각 방으로 확률 계산
for n in range(9):
    alist = []
    while(True):
        arr = arr1[i]
        # 0이면 다음 방의 확률 계산
        if(arr == 0):
            i+=1; 
            break;
        alist.append(arr-1)
        i+=1
    #연결된 각방과 자기자신으로 갈 확률은 모두 같다.
    per = 1/(len(alist)+1)
    mat[n][n] = per
    for m in alist:
        mat[n][m] = per    
        
print(np.round_(mat,4))

[[0.3333 0.3333 0.     0.3333 0.     0.     0.     0.     0.    ]
 [0.25   0.25   0.25   0.     0.25   0.     0.     0.     0.    ]
 [0.     0.3333 0.3333 0.     0.     0.3333 0.     0.     0.    ]
 [0.25   0.25   0.     0.25   0.25   0.     0.     0.     0.    ]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.    ]
 [0.     0.1667 0.1667 0.     0.1667 0.1667 0.     0.1667 0.1667]
 [0.     0.     0.     0.3333 0.     0.     0.3333 0.3333 0.    ]
 [0.     0.     0.     0.     0.2    0.2    0.2    0.2    0.2   ]
 [0.     0.     0.     0.     0.     0.3333 0.     0.3333 0.3333]]


In [219]:
# 쥐는 k = 9 번방에서 시작할때
#시간 1,2,4,9,16초 마다 각방에 쥐가 있을 확률 
tlist = [1,2,4,9,16]
print("k = 9\n")
for t in tlist:
    tempmat = mat
    for n in range(t-1):
        tempmat = np.dot(mat,tempmat)
    print("t =",t)
    for n in range(9):
        print(n+1,"번 방으로 갔을 확률은: ",round(tempmat[8][n],4))
        

k = 9

t = 1
1 번 방으로 갔을 확률은:  0.0
2 번 방으로 갔을 확률은:  0.0
3 번 방으로 갔을 확률은:  0.0
4 번 방으로 갔을 확률은:  0.0
5 번 방으로 갔을 확률은:  0.0
6 번 방으로 갔을 확률은:  0.3333
7 번 방으로 갔을 확률은:  0.0
8 번 방으로 갔을 확률은:  0.3333
9 번 방으로 갔을 확률은:  0.3333
t = 2
1 번 방으로 갔을 확률은:  0.0
2 번 방으로 갔을 확률은:  0.0556
3 번 방으로 갔을 확률은:  0.0556
4 번 방으로 갔을 확률은:  0.0
5 번 방으로 갔을 확률은:  0.1222
6 번 방으로 갔을 확률은:  0.2333
7 번 방으로 갔을 확률은:  0.0667
8 번 방으로 갔을 확률은:  0.2333
9 번 방으로 갔을 확률은:  0.2333
t = 4
1 번 방으로 갔을 확률은:  0.0551
2 번 방으로 갔을 확률은:  0.1168
3 번 방으로 갔을 확률은:  0.0977
4 번 방으로 갔을 확률은:  0.0615
5 번 방으로 갔을 확률은:  0.1184
6 번 방으로 갔을 확률은:  0.1707
7 번 방으로 갔을 확률은:  0.0826
8 번 방으로 갔을 확률은:  0.1699
9 번 방으로 갔을 확률은:  0.1275
t = 9
1 번 방으로 갔을 확률은:  0.1225
2 번 방으로 갔을 확률은:  0.1827
3 번 방으로 갔을 확률은:  0.12
4 번 방으로 갔을 확률은:  0.0988
5 번 방으로 갔을 확률은:  0.1266
6 번 방으로 갔을 확률은:  0.1218
7 번 방으로 갔을 확률은:  0.0579
8 번 방으로 갔을 확률은:  0.1029
9 번 방으로 갔을 확률은:  0.0668
t = 16
1 번 방으로 갔을 확률은:  0.1366
2 번 방으로 갔을 확률은:  0.1974
3 번 방으로 갔을 확률은:  0.126
4 번 방으로 갔을 확률은:  0.1044
5 번 방으로 갔을 확률은:  0.1279
6 번 방

In [220]:
#markov_chain이 stady state에 도달하는 t
tempmat = np.dot(mat,mat)
tempmat1 = mat
t = 2
while(not(tempmat1 == tempmat).min()):
    tempmat1 = tempmat
    tempmat = np.dot(mat,tempmat)
    t+=1
    if(t >= 700): break;
print("t =",t)
print("행렬의",t,"승")
print(np.round_(tempmat,4))
        

t = 112
행렬의 112 승
[[0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]
 [0.1379 0.1989 0.1267 0.1049 0.1281 0.1124 0.0501 0.0869 0.0542]]


In [221]:
# 탈출구(10번방)가 만들어졌을 때 확률
# 탈출구는 9번방에 25퍼센트 확률로 나갈 수 있다.
mat = np.zeros(100,np.float64)
mat = mat.reshape(10,10)
i = 0
mat[9][9] = 1
# 9번방에서 10번방(탈출구)로의 추가
arr1= [2,4,0,1,3,5,0,2,6,0,1,2,5,0,1,2,3,4,6,7,8,0,2,3,5,8,9,0,4,8,0,5,6,7,9,0,6,8,10,0]
for n in range(9):
    alist = []
    while(True):
        arr = arr1[i]
        if(arr == 0):
            i+=1; 
            break;
        alist.append(arr-1)
        i+=1
    per = 1/(len(alist)+1)
    mat[n][n] = per
    for m in alist:
        mat[n][m] = per    

print(np.round_(mat,4))

tlist = [1,2,4,9,16]
print("k = 9\n")
for t in tlist:
    tempmat = mat
    for n in range(t-1):
        tempmat = np.dot(mat,tempmat)
    print("t =",t)
    for n in range(9):
        print(n+1,"번 방에서 출발해 탈출할 확률:",round(tempmat[n][9],4))
        

[[0.3333 0.3333 0.     0.3333 0.     0.     0.     0.     0.     0.    ]
 [0.25   0.25   0.25   0.     0.25   0.     0.     0.     0.     0.    ]
 [0.     0.3333 0.3333 0.     0.     0.3333 0.     0.     0.     0.    ]
 [0.25   0.25   0.     0.25   0.25   0.     0.     0.     0.     0.    ]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.     0.    ]
 [0.     0.1667 0.1667 0.     0.1667 0.1667 0.     0.1667 0.1667 0.    ]
 [0.     0.     0.     0.3333 0.     0.     0.3333 0.3333 0.     0.    ]
 [0.     0.     0.     0.     0.2    0.2    0.2    0.2    0.2    0.    ]
 [0.     0.     0.     0.     0.     0.25   0.     0.25   0.25   0.25  ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     1.    ]]
k = 9

t = 1
1 번 방에서 출발해 탈출할 확률: 0.0
2 번 방에서 출발해 탈출할 확률: 0.0
3 번 방에서 출발해 탈출할 확률: 0.0
4 번 방에서 출발해 탈출할 확률: 0.0
5 번 방에서 출발해 탈출할 확률: 0.0
6 번 방에서 출발해 탈출할 확률: 0.0
7 번 방에서 출발해 탈출할 확률: 0.0
8 번 방에서 출발해 탈출할 확률: 0.0
9 번 방에서 출발해 탈출할 확률: 0.25
t = 2
1 번 방에서 출발해 탈출할 확률: 0.0
2 번 방에서 출

In [222]:
#marcov_chain 결국 최종적으로 탈출할 확률
tempmat = np.dot(mat,mat)
tempmat1 = mat
t = 2
while(not(tempmat1 == tempmat).min()):
    tempmat1 = tempmat
    tempmat = np.dot(mat,tempmat)
    t+=1
print("t =",t)
print("행렬의",t,"승")
print(np.round_(tempmat,4))
#모든 방에서는 9번방으로 가는 경로가 있고
#무한히 움직인다면 결국 언젠가는 탈출하게 되어있다.
        

t = 65708
행렬의 65708 승
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
